name: appeal
favicon: null
layout_spectrum: 0.2000924835447222
typography_spectrum: 0.652883505448699
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4419228455517441
  lightness: 0.8131273158360273
  saturation: 0.7763295145705342
  rhythmicContrast: 0.2987377177923918
purpose: []
